---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes

  tasks:
   
  - name: 1.16 Ensure IAM policies that allow full "*:*" administrative privileges are not attached  
    shell: echo "{{ ansible_local.fulladminpriv }}" 
    register: fulladminpriv
    ignore_errors: True
    tags:
      - fulladminpriv
      - 1.16
      - one
      - all

  - name: 1.16 Ensure IAM policies that allow full "*:*" administrative privileges are not attached   
    shell: | 
      for UserName in `aws iam list-users | jq '.Users[].UserName' | sed 's/"//g'`;
      do
      for PolicyArn in `aws iam list-attached-user-policies --user-name $UserName | jq '.AttachedPolicies[].PolicyArn' | sed 's/"//g'`;
      do
      for GroupName in `aws iam list-groups | jq '.Groups[].GroupName' | sed 's/"//g'`;
      do
      for RoleName in `aws iam list-roles | jq '.Roles[].RoleName' | sed 's/"//g'`;
      do
      aws iam list-entities-for-policy --policy-arn $PolicyArn
      aws iam detach-user-policy --user-name $UserName --policy-arn $PolicyArn
      aws iam detach-group-policy --group-name $GroupName --policy-arn $PolicyArn
      aws iam detach-role-policy --role-name $RoleName --policy-arn $PolicyArn
    args:
      executable: /bin/bash
    when: fulladminpriv.stdout.find("FAILED") != -1
    tags:
      - fulladminpriv
      - 1.16
      - one
      - all
