---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:

  - name: 1.9 Ensure IAM password policy prevents password reuse
    shell: echo "{{ ansible_local.passreuse }}"
    register: passreuse
    ignore_errors: True
    tags:
      - passreuse
      - '1.9'
      - one
      - all

  - name: 1.9 Ensure IAM password policy prevents password reuse
    iam_password_policy:
      state: present
      pw_reuse_prevent: 24
    when: passreuse.stdout.find("FAILED") != -1
    tags:
      - passreuse
      - 1.9
      - one
      - all
