---
- hosts: localhost
  gather_facts: no
  become_method: sudo
  become: yes

  tasks: 

  - name:  1.15 Ensure IAM Users Receive Permissions Only Through Groups 
    shell: echo "{{ ansible_local.IAMUsersPermissionGroups }}" 
    register: IAMUsersPermissionGroups
    ignore_errors: True
    tags:
      - IAMUsersPermissionGroups
      - 1.15
      - one
      - all

  - name: 1.15 Ensure IAM Users Receive Permissions Only Through Groups 
    shell: |
      for UserName in `aws iam list-users | jq '.Users[].UserName' | sed 's/"//g'`;
      do
      for PolicyNames in `aws iam list-user-policies --user-name $UserName | jq '.PolicyNames[]' | sed 's/"//g'`;
      do
      for PolicyArn in `aws iam list-attached-user-policies --user-name $UserName | jq '.AttachedPolicies[].PolicyArn' | sed 's/"//g'`;
      do
      aws iam detach-user-policy --user-name $UserName --policy-arn $PolicyArn
      aws iam delete-user-policy --user-name $UserName --policy-name $PolicyNames
      done
      done
      done
    args:
      executable: /bin/bash
  - iam_group:
      name: testgroup1
      managed_policy:
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/AlexaForBusinessFullAccess
      users:
        - mahi-user
        - user1
      state: present
    when: IAMUsersPermissionGroups.stdout.find("FAILED") != -1
    tags:
      - IAMUsersPermissionGroups
      - 1.15
      - one
      - all
