---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 4.11 Ensure a log metric filter and alarm exist for changes to Network Access Control Lists
    community.aws.cloudwatchlogs_log_group_metric_filter:
      log_group_name: cislog1
      filter_name: NetworkACLEvents
      filter_pattern: '{ ($.eventName = CreateNetworkAcl) || ($.eventName = CreateNetworkAclEntry) || ($.eventName = DeleteNetworkAcl) || ($.eventName = DeleteNetworkAclEntry) || ($.eventName = ReplaceNetworkAclEntry) || ($.eventName = ReplaceNetworkAclAssociation) }' 
      state: present
      metric_transformation:
          metric_name: NetworkACLEventsCount
          metric_namespace: CloudTrailMetrics
          metric_value: "1"        
  - name: 4.11 Ensure a log metric filter and alarm exist for changes to Network Access Control Lists
    sns_topic:
      name: "cis-sns"
      state: present
      display_name: "SNS topic"
      subscriptions:
        - endpoint: "+91 7675955514"
          protocol: "sms"
  - name: 4.11 Ensure a log metric filter and alarm exist for changes to Network Access Control Lists 
    community.aws.ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "NACLalarm"
      metric: "NetworkACLEventCount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">="
      threshold: 1
      period: 300
      evaluation_periods: 1
      unit: "Count"
      alarm_actions: ["arn:aws:sns:us-east-1:405042254276:cis-sns"]
