---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 4.12 Ensure a log metric filter and alarm exist for changes to network gateways
    community.aws.cloudwatchlogs_log_group_metric_filter:
      log_group_name: cislog1 
      filter_name: GatewayChanges
      filter_pattern:  '{ ($.eventName = CreateCustomerGateway) || ($.eventName = DeleteCustomerGateway) || ($.eventName = AttachInternetGateway) || ($.eventName = CreateInternetGateway) || ($.eventName = DeleteInternetGateway) || ($.eventName = DetachInternetGateway) }' 
      state: present
      metric_transformation:
          metric_name: GatewayChangesCount
          metric_namespace: CloudTrailMetrics
          metric_value: "1" 
  - name: 4.12 Ensure a log metric filter and alarm exist for changes to network gateways
    sns_topic:
      name: "cic-sns"
      state: present
      display_name: "SNS topic"
      subscriptions:
        - endpoint: "+91 7675955514"                       
          protocol: "sms"                                                                                                                                           
  - name: 4.12 Ensure a log metric filter and alarm exist for changes to network gateways 
    community.aws.ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "NGalarm"
      metric: "GatewayEventCount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">="
      threshold: 1
      period: 300
      evaluation_periods: 1
      unit: "Count"
      alarm_actions: ["arn:aws:sns:us-east-1:405042254276:cis-sns"]
