---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes

  tasks:
 
  - name:  4.1 Ensure a log metric filter and alarm exist for unauthorized API calls  
    shell: echo "{{ ansible_local.lodgmetralaforunauthcalls }}" 
    register: lodgmetralaforunauthcalls
    ignore_errors: True
    tags:
      - lodgmetralaforunauthcalls
      - '4.1'
      - four
      - all

  - name:  4.1 Ensure a log metric filter and alarm exist for unauthorized API calls 
    community.aws.cloudwatchlogs_log_group_metric_filter:
      log_group_name: cislog1
      filter_name: APICALLS
      filter_pattern: '{ ($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*") }'
      state: present
      metric_transformation:
          metric_name: APICALLSCount
          metric_namespace: CloudTrailMetrics
          metric_value: "1"
    when: lodgmetralaforunauthcalls.stdout.find("FAILED") != -1
    tags:
      - lodgmetralaforunauthcalls
      - '4.1'
      - four
      - all

  - name:  4.1 Ensure a log metric filter and alarm exist for unauthorized API calls
    sns_topic:
      name: "cis-sns"
      state: present
      display_name: "SNS topic"
      subscriptions:
        - endpoint: "+91 7675955514"
          protocol: "sms"
    when: lodgmetralaforunauthcalls.stdout.find("FAILED") != -1
    tags:
      - lodgmetralaforunauthcalls
      - '4.1'
      - four
      - all

  - name:  4.1 Ensure a log metric filter and alarm exist for unauthorized API calls
    ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "apialarm"
      metric: "APICALLSCount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">="
      threshold: 1.0
      period: 300
      evaluation_periods: 1
      unit: "Count"
      alarm_actions: ["arn:aws:sns:us-east-1:405042254276:cis-sns"]
    when: lodgmetralaforunauthcalls.stdout.find("FAILED") != -1
    tags:
      - lodgmetralaforunauthcalls
      - '4.1'
      - four
      - all
