---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes
  tasks:
  - name: 4.7 Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs 
    community.aws.cloudwatchlogs_log_group_metric_filter:
      log_group_name: cislog7
      filter_name: DeletionCMK
      filter_pattern: '{($.eventSource = kms.amazonaws.com) && (($.eventName=DisableKey)||($.eventName=ScheduleKeyDeletion))}'  
      state: present
      metric_transformation:
          metric_name: DeletionCMKCount
          metric_namespace: CloudTrailMetrics
          metric_value: "1
  - name: 4.7 Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs 
    sns_topic:
      name: "cis-sns"
      state: present
      display_name: "SNS topic"
      subscriptions:
        - endpoint: "+91 7675955514" 
          protocol: "sms"
  - name: 4.7 Ensure a log metric filter and alarm exist for disabling or scheduled deletion of customer created CMKs 
    community.aws.ec2_metric_alarm:
      state: present
      region: us-east-1
      name: "CMKalarm"
      metric: "DeletionCMKCount"
      namespace: "CloudTrailMetrics"
      statistic: "Minimum"
      comparison: ">="
      threshold: 1
      period: 300
      evaluation_periods: 1
      unit: "Count"
      alarm_actions: ["arn:aws:sns:us-east-1:405042254276:cis-sns"]
