---
- hosts: localhost
  gather_facts: no
  become_method: sudo
  become: yes

  tasks:

  - name: 3.11 Ensure that Object-level logging for read events is enabled for S3 bucket
    shell: echo "{{ ansible_local.objlogread }}" 
    register: objlogread
    ignore_errors: True
    tags:
      - objlogread
      - '3.11'
      - three
      - all

  - name: 3.11 Ensure that Object-level logging for read events is enabled for S3 bucket
    shell: |
      for TrailName in `aws cloudtrail describe-trails | jq '.trailList[].Name' | sed 's/"//g'`;
      do
      for BucketName in `aws cloudtrail describe-trails | jq -r '.trailList' | jq '.[] | select(.Name=="'$TrailName'")' | jq -r '.S3BucketName'`;
      do
      aws cloudtrail put-event-selectors --region us-east-1 --trail-name $TrailName --event-selectors '[{ "ReadWriteType": "ReadOnly", "IncludeManagementEvents":true, "DataResources": [{ "Type": "AWS::S3::Object", "Values": ["arn:aws:s3:::'$BucketName'/"] }] }]'
      done
      done
    args:
      executable: /bin/bash
    when: objlogread.stdout.find("FAILED") != -1
    tags:
      - objlogread
      - '3.11'
      - three
      - all  
