---
- hosts: localhost
  gather_facts: no
  become_method: sudo
  become: yes
  tasks:

  - name: 3.1(a) Ensure CloudTrail is enabled in all regions
    cloudtrail:
      state: present
      name: "{{ item.name }}"
      s3_bucket_name: "{{ item.s3_bucket_name }}"
      region: "{{ item.region }}"
      is_multi_region_trail: true
    with_items:
      - { name: dap, s3_bucket_name: amn, region: us-east-1}
      - { name: pad, s3_bucket_name: amn, region: us-east-1}
