---
- hosts: localhost
  gather_facts: yes
  become_method: sudo
  become: yes

  tasks:
  - name: 5.2(a) Ensure no security groups allow ingress from 0.0.0.0/0 to remote server administration ports 
    shell: echo "{{ ansible_local.securitygrping }}" 
    register: securitygrping
    ignore_errors: True
    tags:
      - securitygrping
      - '5.2'
      - five
      - all

  - name: 5.2(b) Ensure no security groups allow ingress from 0.0.0.0/0 to remote server administration ports 
    shell: |
      for GroupName in `aws ec2 describe-security-groups | jq '.SecurityGroups[].GroupName' | sed 's/"//g'`;
      do
      aws ec2 revoke-security-group-ingress --group-name $GroupName --protocol tcp --port 22 --cidr 0.0.0.0/0
      aws ec2 revoke-security-group-ingress --group-name $GroupName --protocol tcp --port 3389 --cidr 0.0.0.0/0
      done
    args:
      executable: /bin/bash
    when: securitygrping.stdout.find("FAILED") != -1
    tags:
      - securitygrping
      - '5.2'
      - five
      - all 
